
CREATE TABLE Angajati (
    id_angajat NUMBER PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    functie VARCHAR2(50) NOT NULL,
    salariu NUMBER NOT NULL,
    data_angajare DATE DEFAULT SYSDATE,
    mail VARCHAR2(100) NOT NULL
);

CREATE TABLE Distribuitori_livrari (
    id_distribuitor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zona_livrare VARCHAR2(50) NOT NULL,
    numar_livrari NUMBER NOT NULL,
    id_angajat NUMBER REFERENCES Angajati(id_angajat)
);

CREATE TABLE Angajati_logistica (
    id_angajat_logistica NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel_acces VARCHAR2(50) NOT NULL,
    id_angajat NUMBER REFERENCES Angajati(id_angajat)
);

CREATE TABLE Personal_restaurant (
    id_personal_restaurant NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol VARCHAR2(50) NOT NULL,
    id_angajat NUMBER REFERENCES Angajati(id_angajat)
);

CREATE TABLE Clienti (
    id_client NUMBER PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    nr_tel VARCHAR2(15) NOT NULL,
    mail VARCHAR2(100) NOT NULL
);

CREATE TABLE Meseni (
    id_mesean NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loc_masa NUMBER NOT NULL,
    id_client NUMBER REFERENCES Clienti(id_client)
);

CREATE TABLE Invitati_eveniment (
    id_invitat_eveniment NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tip_invitat VARCHAR2(50) NOT NULL CHECK (tip_invitat IN ('VIP', 'standard', 'copil')),
    masa_invitat NUMBER NOT NULL,
    id_client NUMBER REFERENCES Clienti(id_client)
);

CREATE TABLE Clienti_online (
    id_client_online NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adresa VARCHAR2(100) NOT NULL,
    id_client NUMBER REFERENCES Clienti(id_client)
);

CREATE TABLE COMENZI (
    id_comanda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_comanda DATE DEFAULT SYSDATE,
    ora_livrare VARCHAR(10) NOT NULL, 
    -- CHECK ( REGEXP_LIKE(ora_livrare, '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$') ),
    status VARCHAR2(50) NOT NULL CHECK (status IN ('plasata', 'in curs de livrare', 'livrata', 'anulata')),
    pret NUMBER NOT NULL,
    id_distribuitor NUMBER REFERENCES Distribuitori_livrari(id_distribuitor),
    id_logistician NUMBER REFERENCES Angajati_logistica(id_angajat_logistica),
    id_personal_restaurant NUMBER REFERENCES Personal_restaurant(id_personal_restaurant),
    id_client_online NUMBER REFERENCES Clienti_online(id_client_online)
);

CREATE TABLE Note_plata (
    id_nota_plata NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valoare_totala NUMBER NOT NULL,
    metoda_plata VARCHAR2(50) NOT NULL CHECK (metoda_plata IN ('Cash', 'Card')),
    id_mesean NUMBER REFERENCES Meseni(id_mesean)
);

CREATE TABLE Rezervari (
    id_rezervare NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_rezervare DATE NOT NULL,
    ora_rezervare VARCHAR(10) NOT NULL CHECK ( REGEXP_LIKE(ora_rezervare, '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$') ),
    numar_persoane NUMBER NOT NULL,
    id_mesean NUMBER REFERENCES Meseni(id_mesean)
);

CREATE TABLE Meniuri (
    id_meniu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denumire VARCHAR2(50) NOT NULL,
    descriere VARCHAR2(200) NOT NULL,
    categorie_produse VARCHAR2(50) NOT NULL
);

CREATE TABLE Produse_inventar (
    id_produs_inventar NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_produs VARCHAR2(50) NOT NULL,
    cantitate NUMBER NOT NULL,
    unitate_masura VARCHAR2(20) NOT NULL CHECK (unitate_masura IN ('buc' , 'portie', 'sticla', 'pahar')),
    pret_unitar NUMBER NOT NULL,
    pret NUMBER NOT NULL CHECk(pret>0),
    id_meniu NUMBER REFERENCES Meniuri(id_meniu)
);

CREATE TABLE Evenimente (
    id_eveniment NUMBER PRIMARY KEY,
    tip_eveniment VARCHAR2(50) NOT NULL,
    data_eveniment DATE NOT NULL,
    numar_persoane NUMBER NOT NULL
);

CREATE TABLE Oferte (
    id_oferta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount NUMBER NOT NULL,
    data_expirare DATE NOT NULL
);

CREATE TABLE Sali (
    id_sala NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_sala VARCHAR2(50) NOT NULL,
    capacitate NUMBER NOT NULL
);

CREATE TABLE Animatori (
    id_animator NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_animator VARCHAR2(50) NOT NULL,
    tip_activitate VARCHAR2(50) NOT NULL,
    pret_ora NUMBER NOT NULL
);

CREATE TABLE Comenzi_produse (
    id_comanda NUMBER,
    id_produs_inventar NUMBER,
    pret NUMBER NOT NULL CHECk(pret>0),
    PRIMARY KEY (id_comanda, id_produs_inventar),
    FOREIGN KEY (id_comanda) REFERENCES COMENZI(id_comanda),
    FOREIGN KEY (id_produs_inventar) REFERENCES Produse_inventar(id_produs_inventar)
);

CREATE TABLE Detalii_comanda (
    id_nota_plata NUMBER,
    id_produs_inventar NUMBER,
    pret NUMBER NOT NULL CHECk(pret>0),
    PRIMARY KEY (id_nota_plata, id_produs_inventar),
    FOREIGN KEY (id_nota_plata) REFERENCES Note_plata(id_nota_plata),
    FOREIGN KEY (id_produs_inventar) REFERENCES Produse_inventar(id_produs_inventar)
);

CREATE TABLE Participari_evenimente (
    id_eveniment NUMBER,
    id_invitat_eveniment NUMBER,
    PRIMARY KEY (id_eveniment, id_invitat_eveniment),
    FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment),
    FOREIGN KEY (id_invitat_eveniment) REFERENCES Invitati_eveniment(id_invitat_eveniment)
);

CREATE TABLE Meniuri_evenimente (
    id_meniu NUMBER,
    id_eveniment NUMBER,
    PRIMARY KEY (id_meniu, id_eveniment),
    FOREIGN KEY (id_meniu) REFERENCES Meniuri(id_meniu),
    FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment)
);

CREATE TABLE Colaborari (
    id_eveniment NUMBER,
    id_animator NUMBER,
    PRIMARY KEY (id_eveniment, id_animator),
    FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment),
    FOREIGN KEY (id_animator) REFERENCES Animatori(id_animator)
);

CREATE TABLE Liste_reduceri (
    id_oferta NUMBER,
    id_produs_inventar NUMBER,
    PRIMARY KEY (id_oferta, id_produs_inventar),
    FOREIGN KEY (id_oferta) REFERENCES Oferte(id_oferta),
    FOREIGN KEY (id_produs_inventar) REFERENCES Produse_inventar(id_produs_inventar)
);

CREATE TABLE Planificari_organizatorice (
    id_angajat NUMBER,
    id_eveniment NUMBER,
    id_sala NUMBER,
    observatii VARCHAR2(200),
    PRIMARY KEY (id_angajat, id_eveniment, id_sala),
    FOREIGN KEY (id_angajat) REFERENCES Angajati(id_angajat),
    FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment),
    FOREIGN KEY (id_sala) REFERENCES Sali(id_sala)
);

-- DROP TABLE Clienti CASCADE CONSTRAINTS;
-- DROP TABLE Angajati CASCADE CONSTRAINTS;
-- DROP TABLE Distribuitori_livrari CASCADE CONSTRAINTS;
-- DROP TABLE Angajati_logistica CASCADE CONSTRAINTS;
-- DROP TABLE Personal_restaurant CASCADE CONSTRAINTS;
-- DROP TABLE EVENIMENTE CASCADE CONSTRAINTS;
-- DROP TABLE MENIURI CASCADE CONSTRAINTS;
-- DROP TABLE MENIURI_EVENIMENTE CASCADE CONSTRAINTS;
DROP TABLE Produse_inventar CASCADE CONSTRAINTS;
-- DROP TABLE Oferte CASCADE CONSTRAINTS;
-- DROP TABLE Sali CASCADE CONSTRAINTS;
-- DROP TABLE Animatori CASCADE CONSTRAINTS;
-- DROP TABLE Clienti_online CASCADE CONSTRAINTS;
-- DROP TABLE Colaborari CASCADE CONSTRAINTS;
-- DROP TABLE Participari_evenimente CASCADE CONSTRAINTS;
-- DROP TABLE Planificari_organizatorice CASCADE CONSTRAINTS;
-- DROP TABLE Meseni CASCADE CONSTRAINTS;
-- DROP TABLE Invitati_eveniment CASCADE CONSTRAINTS;
-- DROP TABLE Liste_reduceri CASCADE CONSTRAINTS;
-- DROP TABLE COMENZI CASCADE CONSTRAINTS;
-- DROP TABLE Comenzi_produse CASCADE CONSTRAINTS;
-- DROP TABLE Note_plata CASCADE CONSTRAINTS;
DROP TABLE Detalii_comanda CASCADE CONSTRAINTS;
-- DROP TABLE Rezervari CASCADE CONSTRAINTS;
